import type { Metadata } from "next";
import { Open_Sans} from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({ 
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  style: ['normal', 'italic'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${openSans.className}  bg-[#E7F1E9] antialiased`}>
      <body
      >
        {children}
      </body>
    </html>
  );
}

